<?php
include 'config.php';
if(isset($_REQUEST['signup']))
{
    header("location:signup.php");
}
if(isset($_REQUEST['login']))
{
    header("location:index.php");
}


if(isset($_REQUEST['send']))
{
    if($_REQUEST["email"]!='')
    {
        $query=mysqli_query($con,"select * from login where s_id='".$_REQUEST['email']."'");
        if(mysqli_num_rows($query)<=0)
        {
            $resp_otp='Account not Found for this email';
        }
        else
        {
            $email=($_REQUEST["email"]);
            $randotp=rand(1000,9999);
//             echo $randotp;
            setcookie("randotp",$randotp);
            //$name=$_REQUEST["name"];
            
            
            include 'mail/email.php';
            $msg="Dear  ,
            
      <p>Your OTP is $randotp</p>
      
      <p style='color:red;'>........this is a autogenerated mail don't reply to it........</p>";
            
            
            $mail->From = $from1;
            $mail->FromName = "Online Admission System"; // Name to indicate where the email came from when the recepient received
            $mail->AddAddress($email); // this is for receiver mail id
            $mail->WordWrap = 50; // set word wrap
            $mail->IsHTML(true); // send as HTML
            $mail->Subject = "Username and Password Comfirmation-: "; //used for mail subject
            $mail->Body =$msg; //HTML Body
            if(!$mail->Send())
            {
                $resp_otp='OTP has not Sent.';
            }
            else
            {
                $resp_otp='OTP has Sent Successfully.';
                //echo " OTP has Sent Successfully.";
            }
        }
    }
    else
    {
        $resp_otp='Enter Email ID first';
    }
}
if(isset($_REQUEST['verify']))
{
    $otp=$_REQUEST['otp'];
    $email=$_REQUEST['email'];
    if($otp!='')
    {
        if($otp==$_COOKIE['randotp'])
        {
            $resp_verify="otp matched  , password has sent to your email";
            require_once 'mail-forgotpass.php';
        }
        else
        {
            $resp_verify="otp mismatched";
        }
    }
    elseif($otp=='' && $email=='')
    {
        $resp_otp='Enter Email ID first';
    }
    else
    {
        $resp_verify='Enter OTP';
    }
}


?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
       <link rel="stylesheet" href="bootstrap/bootstrap.min.css">
         <link rel="stylesheet" href="bootstrap/bootstrap-theme.min.css">
       <script src="bootstrap/jquery.min.js"></script>
        <script src="bootstrap/bootstrap.min.js"></script>
        <script language="javascript" type="text/javascript" src="jquery/jquery-1.10.2.js"></script>
        <script language="javascript" type="text/javascript" src="jquery/jquery-ui.js"></script>
        <link href="jquery/jquery-ui.css" rel="stylesheet" type="text/css" />
       <link type="text/css" rel="stylesheet" href="css/sign.css"></link>

    </head>
    <style>.resp{color:darkblue} .error{color: red;font-size: 20} .reg{color:green;font-size: 20}</style>
    
    <body style="background-image:url('./images/inbg.jpg');">
        <form id="signup" action="forgotpass.php" method="post">
             <div style="background-color:cyan; ;margin-top: 100px;margin-left: 400px;margin-right: 400px;">
                 <br><span class="error"  style="margin-left:30px;">
                 <?php
                 if(isset($_REQUEST['send']) || isset($_REQUEST['verify'])) {echo $resp_otp;}
                 if(isset($_REQUEST['verify'])) {echo $resp_verify;}
                 ?>
                 </span><br>
                 <span class="reg" style="margin-left: 30px;">
                 </span><br>
            <font style="color:black; margin-left:200px; font-size:22px; font-family: verdana;font-weight: bold;">Forgot Password</font>
            <br><br>
                    <table id="tabintro" style="text-align: center">
                <tr>
                    <td>
                        <font style="color:black; margin-left:30px; font-family: Verdana;  margin-top:15px; font-size:17px;">Enter Email : * </font>
                    </td>
                </tr>
                <tr>
                    <td  style="padding-bottom: 1em;">
                        <input type="email" id="email" name="email" value="<?php if(isset($_REQUEST['email'])) echo $_REQUEST['email'] ?>">
                    </td>
                    <td> 
                           <input type="submit" id="send" name="send" value="Send OTP"  style="margin-top: 8px;margin-left:90px;" class="toggle btn btn-danger">
                    </td>
                </tr>
                
                 <tr>
                    <td>
                       <font style="color:black; margin-left:30px; font-family: Verdana;font-size:17px;"> Enter OTP : * <font>
                    </td>
                 </tr>
                 <tr>
                    <td  style="padding-bottom: 1em;">
                        <input type="text" id="otp" name="otp" value="<?php if(isset($_REQUEST['otp'])) echo $_REQUEST['otp']; ?>">
                    </td>
                     <td> 
                           <input type="submit" id="verify" name="verify" value="Verify OTP"  style="margin-top: 8px;margin-left:90px;" class="toggle btn btn-danger">
                    </td>
                </tr>
                
                
                <tr>
                    <td> 
                           <input type="submit" id="signup" name="signup" value="SIGN UP"  style="margin-top: 8px;margin-left:90px;" class="toggle btn btn-primary">
                           <input type="submit" id="login" name="login" value="LOGIN"  style="margin-top: 8px;margin-left:90px;" class="toggle btn btn-primary">
                           
                    </td>
                    
                </tr>
                </table>
            <br><br>
            </div>
        </form>
    </body>
</html>
