<?php
include 'config.php';
    
    include 'mail/email.php';
    $msg="Dear '".$result3["s_first_name"]."',
        <p>Your Application for Online Admission has Rejected</p>
        <p>Best of Luck for future</p>

        <p>Application ID : '".$result1["s_detid"]."' </p>
        <p>Course Name : '".$result1["c_name"]."' </p>
        <p>Institute Name : '".$result1["i_name"]."'</p>
        <p>Rejection Reason : '".$reason."'</p>
      
      <p style='color:red;'>........this is a autogenerated mail don't reply to it........</p>";
    
    
    $mail->From = $from1;
    $mail->FromName = "Online Admission System"; // Name to indicate where the email came from when the recepient received
    $mail->AddAddress($eml); // this is for receiver mail id
    $mail->WordWrap = 50; // set word wrap
    $mail->IsHTML(true); // send as HTML
    $mail->Subject = "Course Rejection-: "; //used for mail subject
    $mail->Body =$msg; //HTML Body
    if(!$mail->Send())
    {
        echo "<script>alert('Please , connect to internet or your internet is low');  window.location.href='admin.php'</script>";
    }
    else
    {
        echo "<script>alert('Rejection Mail has sent to the student');  window.location.href='admin.php'</script>";
    }

?>
