<?php
include 'config.php';

$fname=$_REQUEST['fname'];
    
    include 'mail/email.php';
    $msg="Dear $fname ,
        <p>You have filled your admission details successfully</p>

      <p>log in with your username and password to apply for course </p>
      
      <p style='color:red;'>........this is a autogenerated mail don't reply to it........</p>";
    
    
    $mail->From = $from1;
    $mail->FromName = "Simple Institude"; // Name to indicate where the email came from when the recepient received
    $mail->AddAddress($eml); // this is for receiver mail id
    $mail->WordWrap = 50; // set word wrap
    $mail->IsHTML(true); // send as HTML
    $mail->Subject = "Username and Password Comfirmation-: "; //used for mail subject
    $mail->Body =$msg; //HTML Body
    if(!$mail->Send())
    {
        echo "Your internet is slow<br>";
    }
    else
    {
        echo "<script>alert('form-email sent successfully')</script>";
    }